enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 8
remove-rv-integrations-checks = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "RVXA"
build-mode = "both"
module-prop-name = "rvxa-yt-kaif"
patches-version = "v4.2.0"
version = "auto"
included-patches = "'Hide shortcuts' 'MaterialYou'"
patcher-args = "-e 'Settings for YouTube' -OrvxSettingsLabel=RVXA"

[Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "RVXA"
app-name = "Youtube Music"
build-mode = "both"
module-prop-name = "rvxa-ytm-kaif"
patches-version = "v4.2.0"
version = "auto"
included-patches = "'Enable debug logging' 'Hide overlay filter' 'Hide player overlay filter'"
patcher-args = "-e 'Dark theme' -OmaterialYou=true -e 'Settings for YouTube Music' -OrvxSettingsLabel=RVXA"
