enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
remove-rv-integrations-checks = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVXA"
build-mode = "module"
module-prop-name = "rvxa-yt-kaif"
patches-version = "v3.10.0-dev.5"
version = "auto"
included-patches = "'MaterialYou'"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVXA"
build-mode = "module"
module-prop-name = "rvxa-ytm-kaif"
patches-version = "v3.10.0-dev.5"
version = "8.24.53"
included-patches = "'Hide overlay filter' 'Hide player overlay filter'"
patcher-args = "-e 'Dark theme' -OmaterialYou=true"